name: "F5 XC Bot Defense on RE Deploy"

on:
  push:
    branches:
      - main2
    
jobs:
  first_job:
    name: "Create a file"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull latest code
        run: |
          echo "jani is a good boy" > jani.txt
          cat jani.txt

  second_job:
    name: "Check the file"
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull latest code
        run: cat jani.txt
