name: "Deploy and Destroy Workflows"

on:
  schedule:
    - cron: '30 10 * * 0'
    - cron: '30 11 * * 0'
  workflow_dispatch:
  
jobs:
  usecase_schedule:
    name: "Trigger Actions Schedules"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Deploy workflow
        run: gh workflow run bot-defense-re-deploy.yaml --ref bot-defense-re
        if: github.event.schedule == '30 10 * * 0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      - name: Trigger Destroy workflow
        run: gh workflow run bot-defense-re-destroy.yaml --ref destroy-bot-defense-re
        if: github.event.schedule == '30 11 * * 0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
